name = "D3Trees"
uuid = "e3df1716-f71e-5df9-9e2d-98e193103c45"
repo = "https://github.com/sisl/D3Trees.jl.git"
version = "0.3.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NBInclude", "Base64"]

[compat]
julia = "1"
AbstractTrees = "0.3"
JSON = "0.20, 0.21"
